orders/urls.py
from django.urls import path, include

from orders.views import add_to_basket, remove_from_basket, basket_list

app_name = 'orders'

urlpatterns = [
    path('basket/', include([
        path('', basket_list, name='list'),
        path('<int:product_id>/add/', add_to_basket, name='add'),
        path('<int:product_id>/add/<int:size_id>/', add_to_basket, name='add_with_size'),
        path('<int:product_id>/remove/<int:id_of_many>/', remove_from_basket, name='remove'),
    ])),
]

products/urls.py
from django.urls import path, include

from products import views


urlpatterns = [
    path('', views.goods, name='goods'),
    path('<int:sort_pk>/', views.goods, name='goods_sort'),
    path('product/', include([
        path('<slug:slug_id>/', views.mirror_page, name='mirror'),
        path('<slug:slug_id>/<int:size_id>', views.mirror_page, name='mirror_size'),]))
]

products/models.py
import math

from django.db import models
from django.urls import reverse


# Форма зеркала
class ProductForm(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name


# Тип крепления
class FasteningType(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name


# Manager for Product
class ProductQuerySet(models.QuerySet):
    def all_size(self, product):
        return sorted(
            SizeToProduct.objects.filter(product=product),
            key=lambda item: item.size.widthMirror * item.size.lengthMirror
        )

    def minimal_size(self, product):
        return self.all_size(product)[0]

    def cost(self, product, size=None):
        costProduct = 0
        size = Product.product_manager.minimal_size(product=product) if size is None else size
        size_length = Size.objects.filter(id=size.size.id)[0].lengthMirror / 1000
        size_width = Size.objects.filter(id=size.size.id)[0].widthMirror / 1000
        S = size_width * size_length
        P = 0
        if str(product.form) == "Прямоугольник":
            P = (size_width + size_length) * 2
            costProduct += (S * 1600)  # Зеркало
            costProduct += (P * 100)  # ШЛФ
            costProduct += (math.ceil(P / 3) * 900)  # Профиль
        elif str(product.form) == "Круг":
            S = math.pi * (size_length / 2) ** 2
            P = math.pi * 2 * (size_length / 2)
            costProduct += (S * 1600) * (1.2 if size_length > 1200 else 1.5)  # Зеркало
            costProduct += (P * 100) * 1.2  # ШЛФ
        if PlywoodBasisToProduct.objects.filter(product=product.id).exists():
            for i in range(PlywoodBasisToProduct.objects.filter(product=product.id).count()):
                plywood_basis = (
                    PlywoodBasis.objects.get(id=PlywoodBasisToProduct.objects.filter(product=product.id)[i].basis.id))
                costProduct += float(max(math.ceil(min((size_length, size_width))
                                                   / min((plywood_basis.plywood_length, plywood_basis.plywood_width))),
                                         math.ceil(max((size_length, size_width))
                                                   / max((plywood_basis.plywood_length,
                                                          plywood_basis.plywood_width)))) * plywood_basis.price)
                costProduct += float(plywood_basis.cutting) * P  # Резка
                # costProduct += 600  # Расходники !!!убрать!!!
                # Кромка
            if not BacklightToProduct.objects.filter(product=product.id).exists():
                costProduct += 4000 if S < 2 else 5000 if S < 3 else 6000
        if BacklightToProduct.objects.filter(product=product.id).exists():
            # Добавить рассеиватель
            back_light = \
                TypeBacklight.objects.filter(
                    id=BacklightToProduct.objects.filter(product=product.id)[0].typeBackLight.id)[
                    0]
            costProduct += (math.ceil(P / (5 / back_light.quantityBlocks)) * 800) + (
                    math.ceil(P / 5) * back_light.cost)  # Световая лента
            costProduct += 1100  # Рассходники
            if PlywoodBasisToProduct.objects.filter(product=product.id).exists():  # Работа
                costProduct += 8250 if S < 1 else 9350 if S < 2 else 10450 if S < 3 else 15000
            else:
                costProduct += 7500 if S < 1 else 8500 if S < 2 else 9500 if S < 3 else 12500

        if FrameMirrorToProduct.objects.filter(product=product.id).exists():
            frame_material = \
                FrameMaterial.objects.filter(id=FrameMirrorToProduct.objects.filter(product=product.id)[0].material.id)[
                    0]
            costProduct += math.ceil(P / frame_material.size_price) * float(frame_material.material_price)  # Материал
            if frame_material.with_dye:
                costProduct += 300 if P < 2 else 600 if P < 3 else 1000  # Краска
            costProduct += float(frame_material.price_work_less) if S < 1 else float(
                frame_material.price_work_more)  # Работа
            costProduct += float(frame_material.consumables_price)  # Расходники

        if product.pesostruy:
            costProduct += 2700 * S

        costProduct += 500  # Аренда
        costProduct += 1200  # Доставка
        costProduct += 1000  # Транспорт
        costProduct *= 1.18
        return f'{round(costProduct, -2)}'


class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model)

    def all_size(self, product):
        return self.get_queryset().all_size(product=product)

    def minimal_size(self, product):
        return self.get_queryset().minimal_size(product=product)

    def cost(self, product, size=None):
        return self.get_queryset().cost(product=product, size=size)


# Зеркало
class Product(models.Model):
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField()
    form = models.ForeignKey(to=ProductForm, on_delete=models.CASCADE)
    fastening = models.ForeignKey(to=FasteningType, on_delete=models.CASCADE)
    onMainPage = models.BooleanField()
    pesostruy = models.BooleanField()
    is_published = models.BooleanField(default=False)
    slug = models.SlugField(max_length=255, db_index=True, unique=True)

    objects = models.Manager()
    product_manager = ProductManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('mirror', kwargs={'slug_id': self.slug})


class PlywoodBasis(models.Model):
    name = models.CharField(max_length=128, unique=True)
    price = models.DecimalField(decimal_places=5, max_digits=10)
    plywood_length = models.FloatField()
    plywood_width = models.FloatField()
    cutting = models.DecimalField(decimal_places=5, max_digits=10)

    def __str__(self):
        return f'{self.name} | {self.plywood_width} - {self.plywood_length}'


# База зеркала из Фанеры
class PlywoodBasisToProduct(models.Model):
    basis = models.ForeignKey(to=PlywoodBasis, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.basis} | {self.product}'


# Материал рамы
class FrameMaterial(models.Model):
    name = models.CharField(max_length=128, unique=True)
    consumables_price = models.DecimalField(decimal_places=5, max_digits=10)
    size_price = models.FloatField()
    material_price = models.DecimalField(decimal_places=5, max_digits=10)
    price_work_less = models.DecimalField(decimal_places=5, max_digits=10)
    price_work_more = models.DecimalField(decimal_places=5, max_digits=10)
    with_dye = models.BooleanField()

    def __str__(self):
        return self.name


# Цвет рамы
class FrameColor(models.Model):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name


# Наличие рамы у зеркала
class FrameMirrorToProduct(models.Model):
    material = models.ForeignKey(to=FrameMaterial, on_delete=models.CASCADE)
    color = models.ForeignKey(to=FrameColor, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)

    def __str__(self):
        return f'Материал рамы:{self.material} | Цвет: {self.color} | Название заркала: {self.product}'


# Тип подсветка
class TypeBacklight(models.Model):
    name_for_admin = models.CharField(max_length=128)
    name = models.CharField(max_length=128, unique=True)
    cost = models.IntegerField()
    quantityBlocks = models.IntegerField()

    def __str__(self):
        return f'{self.name_for_admin} | {self.quantityBlocks}'


# Наличие подсветки у зеркала
class BacklightToProduct(models.Model):
    typeBackLight = models.ForeignKey(to=TypeBacklight, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)

    def __str__(self):
        return f'Тип подсветки:{self.typeBackLight} | Название зеркала: {self.product}'


# Размеры зеркала
class Size(models.Model):
    lengthMirror = models.FloatField()
    widthMirror = models.FloatField()

    def __str__(self):
        return f'Длина: {self.lengthMirror} | Ширина: {self.widthMirror}'


# Наличие конкретных размеров у конкретных зеркал
class SizeToProduct(models.Model):
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    size = models.ForeignKey(to=Size, on_delete=models.CASCADE)

    def __str__(self):
        if self == Product.product_manager.minimal_size(product=self.product):
            return f'Размер:{self.size} | Зеркало:{self.product} | Отображение в каталоге: Да'
        else:
            return f'Размер:{self.size} | Зеркало:{self.product} | Отображение в каталоге: Нет'


# Остальные категории
class OtherCategories(models.Model):
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    floorMirror = models.BooleanField()
    dressingRoomMirror = models.BooleanField()
    mosaic = models.BooleanField()

    def __str__(self):
        return f'Напольное: {self.floorMirror} | Гримёрное: {self.dressingRoomMirror} | Мозаичное: {self.mosaic}'


# Фото к зеркалу
class ImageToProduct(models.Model):
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products_images')
    firstPhoto = models.BooleanField()

    def __str__(self):
        return f'Фото для : {self.product} | Первое: {self.firstPhoto}'

products/views.py
from django.shortcuts import render, get_object_or_404

from orders.forms import OrderForm, order_form_create
from orders.models import ProductToOrders
from products.models import *
from django.http import HttpResponse
from pages.views import info_for_page

import math


# Create your views here.

def goods(request, sort_pk=None):
    form = order_form_create(request)
    sort_name = 'сначала популярные'
    data = [{
        "product": i,
        "cost": math.ceil(float(Product.product_manager.cost(product=i))),
        "image": ImageToProduct.objects.get(product=i.id, firstPhoto=True)
    } for i in Product.objects.filter(is_published=True)]
    if sort_pk == 1:
        data = sorted(data, key=lambda item: int(item['cost']))
        sort_name = 'сначала дешевые'
    elif sort_pk == 2:
        data = sorted(data, key=lambda item: int(item['cost']), reverse=True)
        sort_name = 'сначала дорогие'
    context = {
        'sort_name': sort_name,
        'info_for_page': info_for_page,
        'basket':
            {
                f'product {product}': {
                    'name': Product.objects.get(id=product['id']).name,
                    'product': Product.objects.get(id=product['id']),
                    'id_of_many': product['id_of_many'],
                    'image': ImageToProduct.objects.get(product=product['id'], firstPhoto=True).image,
                    'cost': math.ceil(
                        float(
                            Product.product_manager.cost(
                                product=Product.objects.get(id=product['id']),
                                size=Product.product_manager.all_size(
                                    product=Product.objects.get(
                                        id=product['id']
                                    ))[product['size']] if isinstance(product['size'], int) else None
                            )
                        )
                    )
                }
                for product in request.session.get('basket')
            } if request.session.get('basket') else {},
        'form': form
    }

    return render(request, 'products/goods.html', {'mirror': data, 'context': context})


def mirror_page(request, slug_id, size_id=None):
    form = order_form_create(request)
    mirror = get_object_or_404(Product, slug=slug_id)
    context = {
        'mirror': {
            'product': mirror,
            'slag': mirror.slug,
            'cost': math.ceil(float(Product.product_manager.cost(
                product=mirror,
                size=None if size_id is None else Product.product_manager.all_size(product=mirror)[size_id]
            ))),
            'images': ImageToProduct.objects.filter(product=mirror),
            'size': Product.product_manager.minimal_size(product=mirror) if size_id is None else
            Product.product_manager.all_size(product=mirror)[size_id],
            'size_id': size_id if size_id else 0,
            'other_size': [size.size for size in Product.product_manager.all_size(product=mirror)],
            'back_light': (
                TypeBacklight.objects.get(id=BacklightToProduct.objects.get(product=mirror.id).typeBackLight.id).name if
                BacklightToProduct.objects.filter(product=mirror.id).exists() else "нет"
            ).lower(),
            'basis': 'дерево' if PlywoodBasisToProduct.objects.filter(
                product=mirror.id).exists() else "алюминевый профиль"
        },
        'basket':
            {
                f'product {product}': {
                    'name': Product.objects.get(id=product['id']).name,
                    'product': Product.objects.get(id=product['id']),
                    'id_of_many': product['id_of_many'],
                    'image': ImageToProduct.objects.get(product=product['id'], firstPhoto=True).image,
                    'cost': math.ceil(
                        float(
                            Product.product_manager.cost(
                                product=Product.objects.get(id=product['id']),
                                size=Product.product_manager.all_size(
                                    product=Product.objects.get(
                                        id=product['id']
                                    ))[product['size']] if isinstance(product['size'], int) else None
                            )
                        )
                    )
                }
                for product in request.session.get('basket')
            } if request.session.get('basket') else {},
        'info_for_page': info_for_page,
        'for_header': False,
        'form': form
    }

    return render(request, 'products/product_page.html', {'context': context})

products/templates/products/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;700&display=swap" rel="stylesheet">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />
    <link rel="icon" href="">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <title>STEKLO&IDEA</title>
</head>

<body>
    <div class="wrapper">
        <header class="header header-goods">
            <div class="header__block header__block-goods">
                <div class="container">
                    <div class="header__nav-block">
                        <a href="index.html">
                            <p class="header__logo header__logo-goods">STEKLO&IDEA</p>
                        </a>
                        <div class="header__nav">
                            <a class="nav__link" href="">
                                <p class="nav__item nav__item-goods">Каталог</p>
                            </a>
                            <a class="nav__link" href="">
                                <p class="nav__item nav__item-goods">Частые вопросы</p>
                            </a>
                            <a class="nav__link" href="">
                                <p class="nav__item nav__item-goods">Связь с нами</p>
                            </a>
                            <div class="nav__link cart__link__block" href="">
                                <div class="cart__link"></div>
                            </div>
                            <div class="header__burger header__burger-goods">
                                <span></span>
                            </div>
                            <div class="header__burger__block">
                                <div class="burger__nav">
                                    <p class="burger__logo">STEKLO&IDEA</p>
                                    <a class="burger__nav__link" href="goods.html">
                                        <p class="burger__nav__item">Каталог</p>
                                    </a>
                                    <a class="burger__nav__link" href="">
                                        <p class="burger__nav__item">Частые вопросы</p>
                                    </a>
                                    <a class="burger__nav__link" href="">
                                        <p class="burger__nav__item">Связь с нами</p>
                                    </a>
                                    <a class="burger__nav__link" href="">
                                        <p class="burger__nav__item">Популярные зеркала</p>
                                    </a>
                                    <a class="burger__nav__link" href="">
                                        <p class="burger__nav__item">Проекты</p>
                                    </a>
                                    <a class="burger__nav__link" href="">
                                        <p class="burger__nav__item">Процесс разработки</p>
                                    </a>
                                </div>
                                <div class="burger__social">
                                    <a class="social__link" href="">
                                        <img src="{% static '/img/vk.svg' %}" alt="" class="social__item">
                                    </a>
                                    <a class="social__link" href="">
                                        <img src="{% static '/img/tg.svg' %}" alt="" class="social__item">
                                    </a>
                                    <a class="social__link" href="">
                                        <img src="{% static '/img/insta.svg' %}" alt="" class="social__item">
                                    </a>
                                    <a class="social__link" href="">
                                        <img src="{% static '/img/whatsapp.svg' %}" alt="" class="social__item">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="cart__block">
                <div class="cart__header">
                    <p class="cart-header__title">Корзина</p>
                    <div class="cart-header__close"></div>
                </div>
                <div class="cart__main">
                    <div class="cart__items">
                    </div>
                    <div class="cart__order">
                        <p class="order__title">Оформить заказ</p>
                        <div class="order__form">
                            <input class="order-form__input" type="text" placeholder="Имя" name="" id="">
                            <input class="order-form__input" type="text" placeholder="Номер телефона" name="" id="">
                            <input class="order-form__input" type="text" placeholder="Город" name="" id="">
                        </div>
                        <div class="order__btn">Оставить заявку</div>
                    </div>
                </div>
            </div>
        </header>
        {% block content %} {% endblock %}
        <footer class="footer"></footer>
    </div>
</body>

<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="{% static '/js/slick.min.js' %}"></script>

<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
<script src="{% static '/js/index.js' %}"></script>

</html>

products/templates/products/goods.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main class="main main-goods">
    <div class="container">
        <p class="title title-dark">Каталог</p>
        <div class="catalog__block">
            <div class="goods">
                <div class="goods__sort">
                    <p class="goods__sort-title">Сортировка:</p>
                    <div class="goods__sort__choose">
                        <p class="goods__sort-value">{{ context.sort_name }}</p>
                        <div class="sort-arrow"></div>
                    </div>
                </div>
                <div class="goods__sort__block">

                    <div class="goods__sort__item">

                           <input id="sort__radio-1" name="sort__radio-1" class="goods__sort__radio" type="radio">

                        <label for="sort__radio-1">
                            <a href="{% url 'goods' %}"><p class="goods__sort__name">Сначала популярные</p></a>
                        </label>
                    </div>


                    <div class="goods__sort__item">

                            <input id="sort__radio-2" name="sort__radio-2" class="goods__sort__radio" type="radio">

                        <label for="sort__radio-2">
                           <a href="{% url 'goods_sort' sort_pk=1 %}"> <p class="goods__sort__name">Сначала дешевые</p></a>
                        </label>
                    </div>

                    <a href="{% url 'goods_sort' sort_pk=2 %}">
                    <div class="goods__sort__item">

                            <input id="sort__radio-3" name="sort__radio-3" class="goods__sort__radio" type="radio">

                        <label for="sort__radio-3">
                            <a href="{% url 'goods_sort' sort_pk=2 %}"><p class="goods__sort__name">Сначала дорогие</p></a>
                        </label>
                    </div>
                    </a>
                </div>

                <div class="goods__block">
                    {% for product in mirror %}
                    <div class="goods__item">
                        <div class="goods-item__description">
                            <a href="{{ product.product.get_absolute_url }}">
                                <img src="{{ product.image.image.url }}" alt="" class="goods-item__img">
                                <p class="goods-item__name">{{ product.product.name }}</p>
                            </a>
                        </div>
                        <div class="goods-item__buy">
                            <a href="{{ mirror.product.get_absolute_url }}">
                                <p class="buy__cost">от {{ product.cost }} ₽</p>
                            </a>
                            <form action="{% url 'orders:add' product_id=product.product.id %}" method="post">
                                {%csrf_token %}
                                <button type="submit" class="cart">
                                    <p class="cart__txt-mobile">Корзина</p>
                                </button>
                            </form>
                        </div>
                        <div class="goods-line"></div>
                    </div>
                    {% endfor %}
                </div>

            </div>
        </div>
    </div>
</main>
{% endblock %}

products/templates/products/product_page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main class="main main-goods">
    <div class="container">
        <div class="product__block">
            <div class="product__show">
                <div class="product__slide__block">
                    {% for image in context.mirror.images %}
                    <div class="product__slide">
                        <img src="{{ image.image.url }}" alt="" class="product-slide__img">
                    </div>
                    {% endfor %}
                </div>
                <div class="product__subslide__block">
                    {% for image in context.mirror.images %}
                    <div class="product__subslide">
                        <img src="{{ image.image.url }}" alt="" class="product-subslide__img">
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="product__description__block">
                <div class="product__title">
                    <p class="product__name">{{ context.mirror.product.name }}</p>
                    <div class="product__price">от {{ context.mirror.cost }} ₽</div>
                </div>
                <div class="product__description">
                    <p class="description__main">{{ context.mirror.product.description }}</p>
                    <div class="description__characteristic">
                                <span class="characteristic-dark">Размер: </span>
                                <div class="characteristic__choose">
                                    <p class="choose__var-show">{{ context.mirror.size.size }}</p>
                                    <svg width="18" height="11" viewBox="0 0 16 9" fill="none"
                                        xmlns="http://www.w3.org/2000/svg">
                                        <path
                                            d="M7.29289 8.70711C7.68342 9.09763 8.31658 9.09763 8.70711 8.70711L15.0711 2.34315C15.4616 1.95262 15.4616 1.31946 15.0711 0.928932C14.6805 0.538408 14.0474 0.538408 13.6569 0.928932L8 6.58579L2.34315 0.928932C1.95262 0.538408 1.31946 0.538408 0.928932 0.928932C0.538408 1.31946 0.538408 1.95262 0.928932 2.34315L7.29289 8.70711ZM7 7L7 8L9 8L9 7L7 7Z"
                                            fill="#484848" fill-opacity="0.6" />
                                    </svg>
                                    <div class="choose__list">
                                        {% for size in context.mirror.other_size %}
                                            {%if forloop.counter0 == 0 %}
                                            <a href="{% url 'mirror' slug_id=context.mirror.product.slug %}">
                                                <p class="choose__var">{{ size }}</p>
                                            </a>
                                            {% else %}
                                            <a href="{% url 'mirror_size' slug_id=context.mirror.product.slug size_id=forloop.counter0 %}">
                                                <p class="choose__var">{{ size }}</p>
                                            </a>
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                    <p class="description__characteristic">
                        <span class="characteristic-dark">Зеркало: </span>серебро
                    </p>

                    <p class="description__characteristic">
                        <span class="characteristic-dark">Подсветка: </span>{{ context.mirror.back_light }}
                    </p>
                    <p class="description__characteristic">
                        <span class="characteristic-dark">Основа: </span>{{ context.mirror.basis }}
                    </p>
                </div>
                <div class="product__buy">
                    <!-- <p class="buy__annotation">Количество:</p> -->
                    <div class="buy__block">
                        <!-- <div class="buy__count">
                            <div class="count-minus">-</div>
                            <div class="count">1</div>
                            <div class="count-plus">+</div>
                        </div> -->
                        <form action="{% url 'orders:add_with_size' product_id=context.mirror.product.id size_id=context.mirror.size_id%}" method="post">
                            {%csrf_token %}
                            <button class="buy__btn btn btn-dark">Добавить в корзину</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}